### ISSUE TITLE
Need docs on how to incorporate type safety for other plugins.

### ISSUE THREAD

**Issue by naturalethic** [wobsoriano/elysia-autoroutes#1]
How does one, for example, include the type for `jwt` or other plugins in request context?

**Comment by naturalethic** [comment]
Ok yes.  

Also I think that Eden will not work if using autoroutes.

**Comment by framp** [comment]
Made a PR for a completely different approach: https://github.com/wobsoriano/elysia-autoroutes/pull/4

Instead of defining functions with explicit methods, you write a function which transform from app to newApp, scoped to the current path.
A bit less minimalistic but that way you have full compatibility with Elysia and its types

Sample code here: https://github.com/framp/elysia-demo/blob/22abede/src/http/api/books/%5Bid%5D.ts

**Comment by wobsoriano** [comment]
Hey @framp, merged that PR. I fully confirm that types are compatible now :) Love it! Thank you.

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/elysia-autoroutes/pull/4
